package com.mrcoder20.portx.domain.usecase

import com.mrcoder20.portx.domain.model.ScanResult
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlinx.datetime.TimeZone
import kotlinx.datetime.toLocalDateTime

class ExportReportUseCase {
    private val json = Json { 
        prettyPrint = true 
        ignoreUnknownKeys = true
    }

    operator fun invoke(scanResult: ScanResult, format: String = "JSON"): String {
        return when (format.uppercase()) {
            "CSV" -> {
                val sb = StringBuilder()
                sb.append("Port,Protocol,Service,Banner,State\n")
                val proto = scanResult.scanType ?: "TCP"
                scanResult.openPorts.forEach { port ->
                    val service = (scanResult.portServices[port] ?: "unknown")
                        .replace(",", ";")
                        .replace("\n", " ")
                        .replace("\r", "")
                    val banner = (scanResult.portBanners[port] ?: "")
                        .replace(",", ";")
                        .replace("\n", " ")
                        .replace("\r", "")
                    sb.append("$port,$proto,$service,$banner,open\n")
                }
                sb.toString()
            }
            "MD" -> {
                val (formattedDate, formattedTime) = try {
                    val dateTime = kotlin.time.Instant.fromEpochMilliseconds(scanResult.timestamp)
                        .toLocalDateTime(TimeZone.currentSystemDefault())
                    val d = dateTime.date.toString()
                    val t = "${dateTime.time.hour.toString().padStart(2, '0')}:${dateTime.time.minute.toString().padStart(2, '0')}"
                    d to t
                } catch (_: Exception) {
                    "N/A" to "N/A"
                }
                val sb = StringBuilder()
                sb.append("# PortX Scan Report\n\n")
                sb.append("## Summary\n")
                sb.append("- **Target:** `${scanResult.target}`\n")
                sb.append("- **Date:** $formattedDate $formattedTime\n")
                sb.append("- **Security Score:** ${scanResult.securityScore}%\n")
                sb.append("- **Open Ports:** ${scanResult.openPorts.size}\n\n")
                
                sb.append("## Discovered Services\n")
                sb.append("| Port | Service | Banner |\n")
                sb.append("| --- | --- | --- |\n")
                scanResult.openPorts.sorted().forEach { port ->
                    val service = (scanResult.portServices[port] ?: "unknown")
                        .replace("|", "\\|")
                        .replace("\n", " ")
                        .replace("\r", "")
                    val banner = (scanResult.portBanners[port] ?: "-")
                        .replace("|", "\\|")
                        .replace("\n", " ")
                        .replace("\r", "")
                    sb.append("| `$port` | $service | $banner |\n")
                }
                sb.append("\n\n*Generated by PortX Professional Engine*")
                sb.toString()
            }
            else -> json.encodeToString(scanResult)
        }
    }
}
