package com.mrcoder20.portx.domain.usecase

import com.mrcoder20.portx.domain.model.ScanResult
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlinx.datetime.TimeZone
import kotlinx.datetime.toLocalDateTime

class ExportReportUseCase {
    private val json = Json { 
        prettyPrint = true 
        ignoreUnknownKeys = true
    }

    operator fun invoke(scanResult: ScanResult, format: String = "JSON"): String {
        return when (format.uppercase()) {
            "CSV" -> {
                val sb = StringBuilder(maxOf(256, scanResult.openPorts.size * 64 + 128))
                sb.append("Port,Protocol,Service,Banner,State\n")
                val proto = scanResult.scanType ?: "TCP"
                scanResult.openPorts.distinct().sorted().forEach { port ->
                    val service = sanitizeCsvField(scanResult.portServices[port] ?: "unknown")
                    val banner = sanitizeCsvField(scanResult.portBanners[port] ?: "")
                    sb.append("$port,$proto,$service,$banner,open\n")
                }
                sb.toString()
            }
            "MD" -> {
                val (formattedDate, formattedTime) = try {
                    val dateTime = kotlin.time.Instant.fromEpochMilliseconds(scanResult.timestamp)
                        .toLocalDateTime(TimeZone.currentSystemDefault())
                    val d = dateTime.date.toString()
                    val t = "${dateTime.time.hour.toString().padStart(2, '0')}:${dateTime.time.minute.toString().padStart(2, '0')}"
                    d to t
                } catch (_: Exception) {
                    "N/A" to "N/A"
                }
                val firewallStatus = FirewallDetectionUseCase()(scanResult)
                val anomalies = AnomalyDetectionUseCase()(scanResult)

                val sb = StringBuilder(maxOf(512, scanResult.openPorts.size * 96 + 1024))
                sb.append("# PortX Scan Report\n\n")
                sb.append("## Summary\n")
                sb.append("- **Target:** `${scanResult.target}`\n")
                if (!scanResult.deviceName.isNullOrBlank()) {
                    sb.append("- **Device:** ${scanResult.deviceName}\n")
                }
                if (!scanResult.osFingerprint.isNullOrBlank()) {
                    sb.append("- **OS Fingerprint:** ${scanResult.osFingerprint}\n")
                }
                sb.append("- **Date:** $formattedDate $formattedTime\n")
                sb.append("- **Security Score:** ${scanResult.securityScore}%\n")
                sb.append("- **Perimeter Assessment:** $firewallStatus\n")
                sb.append("- **Open Ports:** ${scanResult.openPorts.distinct().size}\n\n")
                
                if (anomalies.isNotEmpty()) {
                    sb.append("## Security Anomalies & Vector Warnings\n")
                    anomalies.forEach { anom ->
                        sb.append("- ⚠️ $anom\n")
                    }
                    sb.append("\n")
                }

                sb.append("## Discovered Services\n")
                sb.append("| Port | Service | Banner |\n")
                sb.append("| --- | --- | --- |\n")
                if (scanResult.openPorts.isEmpty()) {
                    sb.append("| - | No Open Services Found | - |\n")
                } else {
                    scanResult.openPorts.distinct().sorted().forEach { port ->
                        val service = (scanResult.portServices[port] ?: "unknown")
                            .replace("|", "\\|")
                            .replace("\n", " ")
                            .replace("\r", "")
                        val banner = (scanResult.portBanners[port] ?: "-")
                            .replace("|", "\\|")
                            .replace("\n", " ")
                            .replace("\r", "")
                        sb.append("| `$port` | $service | $banner |\n")
                    }
                }
                sb.append("\n\n*Generated by PortX Professional Engine*")
                sb.toString()
            }
            else -> json.encodeToString(scanResult)
        }
    }

    private fun sanitizeCsvField(value: String): String {
        var clean = value.replace(",", ";")
            .replace("\n", " ")
            .replace("\r", "")
            .trim()
        // Neutralize CSV / formula injection (OWASP: =, +, -, @, \t, |)
        if (clean.isNotEmpty() && (clean.startsWith("=") || clean.startsWith("+") || clean.startsWith("-") || clean.startsWith("@") || clean.startsWith("\t") || clean.startsWith("|"))) {
            clean = "'$clean"
        }
        return clean
    }
}

