package com.mrcoder20.portx.domain

import androidx.compose.runtime.Composable

enum class Language(val code: String, val label: String) {
    EN("en", "English"),
    FA("fa", "فارسی"),
    RU("ru", "Русский")
}

object LocalizedStrings {
    private val strings = mapOf(
        "en" to mapOf(
            "dashboard" to "Dashboard",
            "tools" to "Tools",
            "reports" to "Reports",
            "settings" to "Settings",
            "scan" to "SCAN",
            "stop" to "STOP",
            "go" to "GO",
            "target" to "Target IP / Domain",
            "advanced" to "Advanced Parameters",
            "active_services" to "Active Services",
            "security_score" to "Security Score",
            "no_services" to "No Services Found",
            "language" to "Language & Region",
            "theme" to "Appearance",
            "accent" to "Accent Color",
            "dark" to "Dark Mode",
            "light" to "Light Mode",
            "internal_ip" to "Internal IP",
            "public_ip" to "Public IP",
            "interface" to "Network Adapter",
            "refresh" to "Refresh",
            "no_reports" to "No Scan Reports Found",
            "security_trend" to "Security Trend",
            "global_export_format" to "GLOBAL EXPORT FORMAT",
            "format_markdown" to "Markdown (.md)",
            "format_csv" to "CSV Table (.csv)",
            "format_json" to "JSON Schema (.json)",
            "scan_report_deleted" to "Scan report deleted",
            "all_reports_cleared" to "All scan reports cleared",
            "saved_to" to "Saved to",
            "download_failed" to "Download failed",
            "share_failed" to "Share failed",
            "failed_delete_record" to "Failed to delete record",
            "failed_clear_history" to "Failed to clear history",
            "failed_load_records" to "Failed to load records",
            "report_copied_clipboard" to "Report copied to clipboard",
            "no_output_to_copy" to "No output to copy",
            "touch_emulation_active" to "Touch Mode",
            "clear_history_title" to "Clear History?",
            "clear_history_desc" to "Permanently delete all scan records?",
            "clear_all" to "CLEAR ALL",
            "cancel" to "CANCEL",
            "not_enough_data" to "NOT ENOUGH DATA",
            "about" to "About",
            "support" to "Support",
            "feedback" to "Feedback",
            "engine_configuration" to "ENGINE CONFIGURATION",
            "engine_config" to "Engine Config",
            "delete" to "Delete",
            "scan_protocol" to "Scan Protocol",
            "parallel_threads" to "Parallel Threads",
            "connections" to "connections",
            "banner_grabbing" to "Banner Grabbing",
            "full_port_scan" to "Full Port Scan",
            "multi_protocol" to "Multi-Protocol",
            "stealth_mode" to "Stealth Mode",
            "device_environment" to "DEVICE ENVIRONMENT",
            "connection" to "Connection",
            "wifi" to "Wi-Fi",
            "wired" to "Wired",
            "adapter" to "Adapter",
            "tactical_icmp_output" to "TACTICAL ICMP OUTPUT",
            "querying" to "QUERYING...",
            "engine_ready" to "Engine ready...",
            "dns_resolution_records" to "DNS RESOLUTION RECORDS",
            "awaiting_dns" to "Awaiting target resolution...",
            "whois_authority_data" to "WHOIS AUTHORITY DATA",
            "ready_whois" to "Ready to query WHOIS...",
            "copy_whois" to "Copy WHOIS",
            "engine_running" to "ENGINE RUNNING",
            "ready" to "READY",
            "live_engine_logs" to "LIVE ENGINE LOGS",
            "waiting_engine_activity" to "Waiting for engine activity...",
            "found" to "FOUND",
            "scanning_network" to "SCANNING NETWORK...",
            "threats_detected" to "Threats Detected",
            "device_profile" to "Device Profile",
            "firewall_perimeter" to "Perimeter",
            "socket_timeout" to "Socket Timeout",
            "ms" to "ms",
            "port_range" to "Port Range",
            "top_100" to "Top 100",
            "standard_ports" to "1-1024",
            "web_ports" to "Web Ports",
            "custom_range" to "Custom",
            "start_port" to "Start Port",
            "end_port" to "End Port",
            "search_reports" to "Filter by target or device...",
            "no_matching_reports" to "No matching reports found",
            "copy_details" to "Copy Details",
            "copied" to "Copied!",
            "close" to "Close",
            "search_ports_placeholder" to "Search port, service, or banner...",
            "filter_all" to "All",
            "filter_threats" to "Threats",
            "filter_web" to "Web",
            "filter_db" to "Database",
            "filter_remote" to "Remote/Admin",
            "filter_banner" to "With Banner",
            "filter_industrial" to "Industrial / IoT",
            "filter_safe" to "Safe / Standard",
            "filter_infra" to "Infrastructure",
            "filter_identified" to "Identified Services",
            "filter_generic" to "Generic / Reflexive",
            "filter_system_ports" to "System (1-1023)",
            "filter_registered_ports" to "User (1024+)",
            "no_ports_found" to "No ports match search criteria",
            "clear_filter" to "Clear Filter",
            "copy_all_logs" to "Copy All Logs",
            "clear_logs" to "Clear Logs",
            "logs_count" to "Logs",
            "open_ports_count" to "Open Ports",
            "high_risk" to "Critical / High Risk",
            "secure" to "Secure",
            "warning" to "Moderate Risk",
            "packets_tx" to "Sent",
            "packets_rx" to "Received",
            "packet_loss" to "Packet Loss",
            "avg_latency" to "Avg Latency",
            "copy_curl" to "Copy cURL",
            "copy_url" to "Copy URL",
            "engine_standby" to "Engine Standby",
            "engine_active" to "Scanning Active",
            "system_info" to "System & Architecture",
            "runtime_arch" to "Desktop Runtime",
            "quick_localhost" to "Localhost (127.0.0.1)",
            "valid_target_ip" to "IPv4 Target",
            "valid_target_domain" to "Domain Target",
            "whois_summary" to "Domain Summary",
            "registrar" to "Registrar",
            "created_date" to "Created Date",
            "expiry_date" to "Expiry Date",
            "dns_records_count" to "Resolved Records",
            "quick_targets" to "Quick Targets",
            "port_presets" to "Port Profiles",
            "top_20" to "Top 20",
            "top_1000" to "Top 1000",
            "all_65k" to "All 65,535",
            "web_services" to "Web (80, 443)",
            "db_services" to "Database",
            "remote_iot" to "Remote & IoT",
            "logs_tab" to "Live Logs",
            "services_tab" to "Discovered Services",
            "report_detail_title" to "Scan Report Details",
            "executive_summary" to "Executive Summary",
            "discovered_ports" to "Discovered Ports",
            "risk_analysis" to "Risk Analysis",
            "firewall_status" to "Firewall State",
            "anomalies_detected" to "Anomalies",
            "close" to "Close",
            "min_latency" to "Min Latency",
            "max_latency" to "Max Latency",
            "jitter" to "Jitter",
            "scan_subnet" to "Scan Subnet",
            "threat_score" to "Threat Score",
            "grade" to "Grade",
            "copied_to_clipboard" to "Copied to clipboard",
            "app_lifecycle" to "Application Lifecycle & Maintenance",
            "check_updates" to "Check for Updates",
            "up_to_date" to "PortX is up to date",
            "repair_app" to "Repair Installation",
            "repair_desc" to "Reset socket pool and database cache",
            "uninstall_app" to "Uninstall PortX",
            "uninstall_confirm_title" to "Uninstall PortX?",
            "uninstall_confirm_desc" to "This will launch the Windows uninstaller to remove PortX from your system.",
            "launch_uninstaller" to "Launch Uninstaller",
            "placeholder_dns" to "Domain (e.g. google.com)",
            "placeholder_whois" to "Domain (e.g. wikipedia.org)",
            "ping_gateway" to "Ping Gateway",
            "gateway_label" to "Gateway",
            "firewall_open" to "Open Perimeter",
            "firewall_hardened" to "Hardened Perimeter",
            "firewall_standard" to "Standard Network Profile",
            "firewall_filtered" to "Firewall Active",
            "load_more_ports" to "Load More Ports",
            "showing_ports_count" to "Showing {shown} of {total} open ports",
            "no_open_ports" to "No open ports detected. Perimeter is fully sealed.",
            "search_ports_in_report" to "Filter report ports...",
            "device_mode" to "Device Mode",
            "device_responsive" to "Responsive",
            "rotate_device" to "Rotate Screen",
            "snap_window" to "Snap Window to Device",
            "device_frame" to "Device Bezel Frame",
            "os_fingerprint" to "OS Fingerprint",
            "download_report" to "Download",
            "share_report" to "Share",
            "detected_banner" to "DETECTED BANNER / SERVICE SIGNATURE",
            "security_advisory" to "SECURITY ADVISORY & HARDENING",
            "tcp_listening" to "TCP LISTENING",
            "port_open" to "OPEN",
            "export_report" to "Export & Save",
            "export_modal_title" to "Export Scan Report",
            "export_format_label" to "Export Format",
            "preview" to "Live Export Preview",
            "save_as_file" to "Save As...",
            "quick_save_downloads" to "Save to Downloads",
            "share_file_native" to "System Share",
            "copy_content" to "Copy Content",
            "trend_improved" to "Security Improving",
            "trend_declined" to "Security Declining",
            "trend_stable" to "Security Stable",
            "peak_score" to "Peak",
            "min_score" to "Min",
            "avg_score" to "Avg",
            "latest_score" to "Latest",
            "click_to_view" to "Click point to view details",
            "trend_all" to "All Scans",
            "trend_last_10" to "Last 10",
            "trend_last_25" to "Last 25",
            "trend_critical" to "Critical (<50%)",
            "file_size" to "Size",
            "lines_count" to "Lines",
            "core_engine" to "Core Engine",
            "core_engine_val" to "Asynchronous NIO Sockets",
            "threat_intel" to "Threat Intelligence",
            "threat_intel_val" to "NVD / CVE Embedded v2026.1",
            "local_persistence" to "Local Persistence",
            "local_persistence_val" to "Encrypted SQLite Local-First",
            "app_footer_build" to "PortX Professional Cyber Suite v5.3.0 • Production Build",
            "engine_online" to "ENGINE ONLINE",
            "engine_scanning_badge" to "SCANNING",
            "security_suite_sub" to "SECURITY SUITE v5.2",
            "engine_socket_sub" to "Async NIO • TCP/UDP",
            "toggle_theme" to "Toggle Theme",
            "quick_target_localhost" to "Localhost",
            "quick_target_gateway" to "Gateway",
            "quick_target_nmap" to "Nmap Server",
            "tool_local" to "LOCAL",
            "tool_ping" to "PING",
            "tool_dns" to "DNS",
            "tool_whois" to "WHOIS",
            "verified_registrar" to "VERIFIED REGISTRAR",
            "badge_local" to "LOCAL",
            "ping_action" to "Ping",
            "copy_line" to "Copy line",
            "copy" to "Copy",
            "format_markdown" to "Markdown (.md)",
            "format_csv" to "CSV Table (.csv)",
            "format_json" to "JSON Schema (.json)",
            "clear_all_reports" to "Clear All Reports",
            "port_detail_port" to "Port",
            "port_detail_title" to "Title",
            "port_detail_target" to "Target",
            "port_detail_status" to "Status",
            "port_detail_banner" to "Banner",
            "port_detail_risk" to "Risk",
            "port_detail_advisory" to "Advisory",
            "err_enter_ip" to "Please enter an IP or Hostname",
            "err_invalid_target" to "Invalid target format (e.g. 8.8.8.8, router, or example.com)",
            "err_port_range" to "Range must be 1-65535",
            "err_numeric_range" to "Invalid numeric port range",
            "err_enter_dns" to "Please enter a Domain to resolve",
            "err_enter_whois" to "Please enter a domain (e.g. google.com)",
            "err_whois_unreachable" to "WHOIS service unreachable.",
            "err_dns_unreachable" to "No DNS resolution found for target. Check your connection.",
            "err_engine_failure" to "Engine error occurred during network operation.",
            "expand" to "Expand",
            "collapse" to "Collapse",
            "port_category" to "Category",
            "port_rfc" to "Standard & RFC",
            "port_tier" to "Port Tier",
            "port_encryption" to "Encryption",
            "attack_vectors" to "Attack Vectors",
            "common_cves" to "Threat Intel & CVEs",
            "hardening_guide" to "Remediation & Hardening",
            "waf_anomaly_title" to "WAF / SYN-Proxy Anomaly",
            "waf_anomaly_desc" to "The target perimeter is synthetically acknowledging closed ports. Filtered ports are excluded from threat scoring.",
            "privileged_port" to "System / Privileged (0-1023)",
            "registered_port" to "Registered User (1024-49151)",
            "dynamic_port" to "Dynamic / Private (49152-65535)",
            "cat_infra" to "Core Infrastructure",
            "cat_web" to "Web & API Services",
            "cat_remote" to "Remote Administration",
            "cat_database" to "Databases & Cache",
            "cat_files" to "File & Directory Sharing",
            "cat_mail" to "Mail & Messaging",
            "cat_industrial" to "Industrial ICS & SCADA",
            "cat_cloud" to "Cloud & Containers",
            "cat_iot" to "IoT & Embedded",
            "cat_general" to "General Network Service",
            "enc_tls" to "TLS / SSL Encrypted",
            "enc_ssh" to "SSH Encrypted Stream",
            "enc_cleartext" to "Cleartext / Unencrypted",
            "enc_binary" to "Binary RPC Stream",
            "enc_kerberos" to "Kerberos / NTLM Signed",
            "dns_server_used" to "DNS Server",
            "dns_response_time" to "Response Time",
            "dns_records_count" to "Records",
            "dns_view_cards" to "Visual Cards",
            "dns_view_raw" to "Dig / Terminal Stream",
            "dns_dnssec_valid" to "DNSSEC Validated",
            "dns_priority" to "Priority",
            "dns_ttl" to "TTL",
            "dns_filter_all" to "ALL",
            "dns_filter_ip" to "A / AAAA",
            "dns_filter_mx" to "MX (Mail)",
            "dns_filter_txt" to "TXT",
            "dns_filter_ns" to "NS",
            "dns_filter_cname" to "CNAME",
            "dns_filter_soa" to "SOA",
            "dns_filter_caa" to "CAA",
            "dns_filter_ptr" to "PTR",
            "subnet_calculator" to "Subnet & Network CIDR",
            "subnet_cidr" to "Subnet Mask / CIDR",
            "subnet_broadcast" to "Broadcast Address",
            "subnet_range" to "Usable Host Range",
            "subnet_total_hosts" to "Usable Hosts",
            "scan_entire_subnet" to "Scan Entire Subnet",
            "tcp_ping_mode" to "TCP Ping (SYN/ACK)",
            "icmp_ping_mode" to "Standard ICMP",
            "ping_port_label" to "TCP Port"
        ),
        "fa" to mapOf(
            "dashboard" to "داشبورد",
            "tools" to "ابزارها",
            "reports" to "گزارش‌ها",
            "settings" to "تنظیمات",
            "scan" to "اسکن",
            "stop" to "توقف",
            "go" to "اجرا",
            "target" to "آی‌پی یا دامنه هدف",
            "advanced" to "تنظیمات پیشرفته",
            "active_services" to "سرویس‌های فعال",
            "security_score" to "امتیاز امنیتی",
            "no_services" to "سرویسی یافت نشد",
            "language" to "زبان و منطقه",
            "theme" to "ظاهر برنامه",
            "accent" to "رنگ اصلی",
            "dark" to "حالت تاریک",
            "light" to "حالت روشن",
            "internal_ip" to "آی‌پی داخلی",
            "public_ip" to "آی‌پی عمومی",
            "interface" to "کارت شبکه",
            "refresh" to "به‌روزرسانی",
            "no_reports" to "گزارش اسکنی یافت نشد",
            "security_trend" to "روند امنیت",
            "global_export_format" to "فرمت خروجی گزارش",
            "format_markdown" to "مارک‌داون (.md)",
            "format_csv" to "جدول داده‌ها (.csv)",
            "format_json" to "ساختار داده (.json)",
            "scan_report_deleted" to "گزارش اسکن با موفقیت حذف شد",
            "all_reports_cleared" to "تمام گزارش‌های اسکن پاکسازی شدند",
            "saved_to" to "ذخیره شد در",
            "download_failed" to "خطا در دانلود گزارش",
            "share_failed" to "خطا در اشتراک‌گذاری گزارش",
            "failed_delete_record" to "خطا در حذف گزارش",
            "failed_clear_history" to "خطا در پاک‌سازی تاریخچه",
            "failed_load_records" to "خطا در بارگذاری گزارش‌ها",
            "report_copied_clipboard" to "گزارش در حافظه کلیپ‌بورد کپی شد",
            "no_output_to_copy" to "داده‌ای برای کپی وجود ندارد",
            "touch_emulation_active" to "حالت لمسی",
            "clear_history_title" to "پاک‌سازی تاریخچه؟",
            "clear_history_desc" to "تمام سوابق اسکن برای همیشه حذف شوند؟",
            "clear_all" to "حذف همه",
            "cancel" to "انصراف",
            "not_enough_data" to "داده کافی نیست",
            "about" to "درباره ما",
            "support" to "پشتیبانی",
            "feedback" to "بازخورد",
            "engine_configuration" to "پیکربندی موتور اسکن",
            "engine_config" to "تنظیمات موتور",
            "delete" to "حذف",
            "os_fingerprint" to "ردپای سیستم‌عامل",
            "scan_protocol" to "پروتکل اسکن",
            "parallel_threads" to "تعداد کانکشن‌های همزمان",
            "connections" to "اتصال",
            "banner_grabbing" to "دریافت بنر سرویس‌ها",
            "full_port_scan" to "اسکن تمام پورت‌ها (۱-۶۵۵۳۵)",
            "multi_protocol" to "چند پروتکلی (TCP/UDP)",
            "stealth_mode" to "حالت پنهانکار (Stealth)",
            "device_environment" to "اطلاعات کارت شبکه و سیستم",
            "connection" to "نوع اتصال",
            "wifi" to "بی‌سیم (Wi-Fi)",
            "wired" to "کابلی (Ethernet)",
            "adapter" to "کارت شبکه",
            "tactical_icmp_output" to "خروجی بسته‌های پینگ (ICMP)",
            "querying" to "در حال ارسال درخواست...",
            "engine_ready" to "موتور آماده اجرا...",
            "dns_resolution_records" to "رکوردهای تفکیک نام (DNS)",
            "awaiting_dns" to "در انتظار تفکیک دامنه...",
            "whois_authority_data" to "اطلاعات ثبت دامنه (WHOIS)",
            "ready_whois" to "آماده دریافت اطلاعات هویتی دامنه...",
            "copy_whois" to "کپی اطلاعات دامنه",
            "engine_running" to "موتور در حال اسکن",
            "ready" to "آماده",
            "live_engine_logs" to "لاگ زنده وقایع موتور اسکن",
            "waiting_engine_activity" to "در انتظار شروع پردازش...",
            "found" to "مورد شناسایی شد",
            "scanning_network" to "در حال بررسی شبکه...",
            "threats_detected" to "تهدید شناسایی شد",
            "device_profile" to "مشخصات دستگاه",
            "firewall_perimeter" to "محدوده شبکه",
            "socket_timeout" to "مهلت زمانی اتصال",
            "ms" to "میلی‌ثانیه",
            "port_range" to "محدوده پورت‌ها",
            "top_100" to "۱۰۰ پورت پرکاربرد",
            "standard_ports" to "۱ تا ۱۰۲۴ (پیش‌فرض)",
            "web_ports" to "پورت‌های وب",
            "custom_range" to "سفارشی",
            "start_port" to "پورت شروع",
            "end_port" to "پورت پایان",
            "search_reports" to "جستجو بر اساس هدف یا دستگاه...",
            "no_matching_reports" to "گزارشی مطابق جستجو یافت نشد",
            "copy_details" to "کپی جزئیات",
            "copied" to "کپی شد!",
            "close" to "بستن",
            "search_ports_placeholder" to "جستجوی پورت، سرویس یا بنر...",
            "filter_all" to "همه",
            "filter_threats" to "تهدیدات",
            "filter_web" to "وب",
            "filter_db" to "دیتابیس",
            "filter_remote" to "ریموت",
            "filter_banner" to "بنردار",
            "filter_industrial" to "صنعتی",
            "filter_safe" to "امن",
            "filter_infra" to "زیرساخت",
            "filter_identified" to "شناسایی‌شده",
            "filter_generic" to "عمومی",
            "filter_system_ports" to "سیستمی",
            "filter_registered_ports" to "کاربری",
            "no_ports_found" to "هیچ پورتی مطابق با فیلتر یافت نشد",
            "clear_filter" to "پاک‌سازی فیلتر",
            "copy_all_logs" to "کپی همه لاگ‌ها",
            "clear_logs" to "پاک‌سازی لاگ‌ها",
            "logs_count" to "لاگ",
            "open_ports_count" to "پورت باز",
            "high_risk" to "پرخطر / بحرانی",
            "secure" to "امن",
            "warning" to "ریسک متوسط",
            "packets_tx" to "ارسال",
            "packets_rx" to "دریافت",
            "packet_loss" to "افت بسته",
            "avg_latency" to "میانگین تاخیر",
            "copy_curl" to "کپی دستور cURL",
            "copy_url" to "کپی آدرس",
            "engine_standby" to "موتور آماده به کار",
            "engine_active" to "اسکن فعال",
            "system_info" to "مشخصات سیستم و معماری",
            "runtime_arch" to "محیط اجرای دسکتاپ",
            "quick_localhost" to "لوکال‌هاست (127.0.0.1)",
            "valid_target_ip" to "آی‌پی IPv4",
            "valid_target_domain" to "دامنه معتبر",
            "whois_summary" to "خلاصه هویتی دامنه",
            "registrar" to "ثبت‌کننده",
            "created_date" to "تاریخ ایجاد",
            "expiry_date" to "تاریخ انقضا",
            "dns_records_count" to "رکوردهای شناسایی‌شده",
            "quick_targets" to "اهداف سریع",
            "port_presets" to "پروفایل‌های پورت",
            "top_20" to "۲۰ پورت برتر",
            "top_1000" to "۱۰۰۰ پورت استاندارد",
            "all_65k" to "تمام ۶۵٬۵۳۵ پورت",
            "web_services" to "وب (80, 443)",
            "db_services" to "پایگاه داده (DB)",
            "remote_iot" to "دسترسی راه دور و اینترنت اشیا",
            "logs_tab" to "لاگ‌های زنده",
            "services_tab" to "سرویس‌های کشف‌شده",
            "report_detail_title" to "جزئیات گزارش امنیتی",
            "executive_summary" to "خلاصه مدیریتی",
            "discovered_ports" to "پورت‌های شناسایی‌شده",
            "risk_analysis" to "تحلیل سطح مخاطره",
            "firewall_status" to "وضعیت دیواره آتش",
            "anomalies_detected" to "ناهنجاری‌های شبکه",
            "min_latency" to "حداقل تاخیر",
            "max_latency" to "حداکثر تاخیر",
            "jitter" to "نوسان تاخیر",
            "scan_subnet" to "اسکن زیرشبکه محلی",
            "threat_score" to "شاخص ریسک",
            "grade" to "رتبه امنیتی",
            "copied_to_clipboard" to "در حافظه موقت کپی شد",
            "app_lifecycle" to "مدیریت چرخه حیات و نگهداری برنامه",
            "check_updates" to "بررسی به‌روزرسانی",
            "up_to_date" to "برنامه به‌روز است",
            "repair_app" to "تعمیر و بازیابی برنامه",
            "repair_desc" to "بازنشانی حافظه موقت و اعتبارسنجی پایگاه‌داده",
            "uninstall_app" to "حذف کامل برنامه (Uninstall)",
            "uninstall_confirm_title" to "آیا از حذف PortX اطمینان دارید؟",
            "uninstall_confirm_desc" to "این فرآیند دستیار رسمی حذف ویندوز را برای پاک‌سازی PortX از سیستم اجرا می‌کند.",
            "launch_uninstaller" to "اجرای حذف‌کننده ویندوز",
            "placeholder_dns" to "دامنه (مثال: google.com)",
            "placeholder_whois" to "دامنه (مثال: wikipedia.org)",
            "ping_gateway" to "پینگ گیت‌وی",
            "gateway_label" to "گیت‌وی",
            "firewall_open" to "محدوده باز شبکه",
            "firewall_hardened" to "محدوده امن شبکه",
            "firewall_standard" to "پروفایل شبکه استاندارد",
            "firewall_filtered" to "دیواره آتش فعال",
            "load_more_ports" to "بارگذاری پورت‌های بیشتر",
            "showing_ports_count" to "نمایش {shown} از {total} پورت باز",
            "no_open_ports" to "هیچ پورت بازی یافت نشد. محدوده کاملاً امن و مسدود است.",
            "search_ports_in_report" to "فیلتر و جستجوی پورت‌های گزارش...",
            "device_mode" to "شبیه‌ساز دستگاه",
            "device_responsive" to "ریسپانسیو خودکار",
            "rotate_device" to "چرخش صفحه",
            "snap_window" to "تطبیق ابعاد پنجره با دستگاه",
            "device_frame" to "قاب فیزیکی دستگاه",
            "download_report" to "دریافت گزارش",
            "share_report" to "اشتراک‌گذاری",
            "detected_banner" to "امضای سرویس و بنر کشف‌شده",
            "security_advisory" to "توصیه‌های امنیتی و مقاوم‌سازی",
            "tcp_listening" to "در حال شنود (TCP)",
            "port_open" to "پورت باز",
            "export_report" to "خروجی و ذخیره گزارش",
            "export_modal_title" to "خروجی و ذخیره گزارش اسکن",
            "export_format_label" to "فرمت خروجی",
            "preview" to "پیش‌نمایش زنده خروجی",
            "save_as_file" to "ذخیره در مسیر دلخواه...",
            "quick_save_downloads" to "ذخیره در پوشه دانلودها",
            "share_file_native" to "اشتراک‌گذاری سیستمی",
            "copy_content" to "کپی در حافظه",
            "trend_improved" to "بهبود سطح امنیت",
            "trend_declined" to "کاهش سطح امنیت",
            "trend_stable" to "وضعیت امنیتی پایدار",
            "peak_score" to "بیشترین",
            "min_score" to "کمترین",
            "avg_score" to "میانگین",
            "latest_score" to "آخرین",
            "click_to_view" to "کلیک روی نقطه برای مشاهده جزئیات",
            "trend_all" to "همه اسکن‌ها",
            "trend_last_10" to "۱۰ اسکن اخیر",
            "trend_last_25" to "۲۵ اسکن اخیر",
            "trend_critical" to "فقط پرخطرها (<۵۰٪)",
            "file_size" to "حجم",
            "lines_count" to "خط",
            "core_engine" to "موتور هسته",
            "core_engine_val" to "سوکت‌های ناهمگام NIO",
            "threat_intel" to "تحلیل تهدیدات و آسیب‌پذیری",
            "threat_intel_val" to "پایگاه NVD / CVE نسخه 2026.1",
            "local_persistence" to "ذخیره‌سازی محلی",
            "local_persistence_val" to "پایگاه SQLite محلی رمزنگاری‌شده",
            "app_footer_build" to "مجموعه امنیت سایبری حرفه‌ای PortX نسخه 5.3.0 • بیلد رسمی",
            "engine_online" to "موتور آماده",
            "engine_scanning_badge" to "در حال اسکن",
            "security_suite_sub" to "مجموعه امنیت سایبری v5.2",
            "engine_socket_sub" to "سوکت‌های ناهمگام NIO • TCP/UDP",
            "toggle_theme" to "تغییر تم",
            "quick_target_localhost" to "لوکال‌هاست",
            "quick_target_gateway" to "گیت‌وی",
            "quick_target_nmap" to "سرور ان‌مپ",
            "tool_local" to "شبکه محلی",
            "tool_ping" to "پینگ",
            "tool_dns" to "دی‌ان‌اس",
            "tool_whois" to "هویز",
            "verified_registrar" to "ثبت‌کننده تاییدشده",
            "badge_local" to "محلی",
            "ping_action" to "پینگ",
            "copy_line" to "کپی خط",
            "copy" to "کپی",
            "format_markdown" to "مارک‌داون (.md)",
            "format_csv" to "جدول اکسل (.csv)",
            "format_json" to "ساختار JSON (.json)",
            "clear_all_reports" to "پاک‌سازی همه گزارش‌ها",
            "port_detail_port" to "پورت",
            "port_detail_title" to "عنوان",
            "port_detail_target" to "هدف",
            "port_detail_status" to "وضعیت",
            "port_detail_banner" to "بنر",
            "port_detail_risk" to "سطح ریسک",
            "port_detail_advisory" to "توصیه امنیتی",
            "err_enter_ip" to "لطفاً یک آی‌پی یا نام هاست وارد کنید",
            "err_invalid_target" to "فرمت نامعتبر هدف (مثال: 8.8.8.8 یا example.com)",
            "err_port_range" to "محدوده پورت باید بین ۱ تا ۶۵۵۳۵ باشد",
            "err_numeric_range" to "محدوده عددی پورت نامعتبر است",
            "err_enter_dns" to "لطفاً دامنه‌ای برای تفکیک نام وارد کنید",
            "err_enter_whois" to "لطفاً یک دامنه وارد کنید (مثال: google.com)",
            "err_whois_unreachable" to "سرویس WHOIS در دسترس نیست.",
            "err_dns_unreachable" to "هیچ رکوردی برای تفکیک نام هدف یافت نشد. اتصال شبکه را بررسی کنید.",
            "err_engine_failure" to "خطای داخلی موتور در حین عملیات شبکه رخ داد.",
            "expand" to "گسترش",
            "collapse" to "جمع‌کردن",
            "port_category" to "دسته‌بندی",
            "port_rfc" to "استاندارد و RFC",
            "port_tier" to "طبقه پورت",
            "port_encryption" to "رمزنگاری",
            "attack_vectors" to "بردارهای حمله متداول",
            "common_cves" to "تحلیل آسیب‌پذیری و CVEها",
            "hardening_guide" to "دستورالعمل امن‌سازی و رفع خطر",
            "waf_anomaly_title" to "ناهنجاری WAF / فایروال پروکسی",
            "waf_anomaly_desc" to "فایروال یا WAF لایه لبه این هدف به تمامی پورت‌ها پاسخ ساختگی می‌دهد. پورت‌های بازتابی در امتیازدهی فیلتر شدند.",
            "privileged_port" to "پورت سیستمی / ممتاز (۰-۱۰۲۳)",
            "registered_port" to "پورت ثبت‌شده کاربری (۱۰۲۴-۴۹۱۵۱)",
            "dynamic_port" to "پورت پویا / خصوصی (۴۹۱۵۲-۶۵۵۳۵)",
            "cat_infra" to "زیرساخت هسته شبکه",
            "cat_web" to "وب و وب‌سرویس‌ها",
            "cat_remote" to "مدیریت دسترسی از راه دور",
            "cat_database" to "پایگاه‌های داده و کش",
            "cat_files" to "اشتراک‌گذاری فایل و دایرکتوری",
            "cat_mail" to "پست الکترونیک و پیام‌رسانی",
            "cat_industrial" to "سامانه‌های صنعتی و اسکادا",
            "cat_cloud" to "ابری و کانتینرها",
            "cat_iot" to "اینترنت اشیا و دستگاه‌های هوشمند",
            "cat_general" to "سرویس عمومی شبکه",
            "enc_tls" to "رمزنگاری TLS / SSL",
            "enc_ssh" to "جریان رمزنگاری‌شده SSH",
            "enc_cleartext" to "متن ساده / فاقد رمزنگاری",
            "enc_binary" to "جریان باینری RPC",
            "enc_kerberos" to "احراز هویت Kerberos / NTLM",
            "dns_server_used" to "سرور دی‌ان‌اس",
            "dns_response_time" to "زمان پاسخ",
            "dns_records_count" to "رکورد",
            "dns_view_cards" to "کارت‌های بصری",
            "dns_view_raw" to "خروجی ترمینال / Dig",
            "dns_dnssec_valid" to "تایید شده با DNSSEC",
            "dns_priority" to "اولویت",
            "dns_ttl" to "طول عمر رکورد (TTL)",
            "dns_filter_all" to "همه",
            "dns_filter_ip" to "A / AAAA",
            "dns_filter_mx" to "سرورهای ایمیل (MX)",
            "dns_filter_txt" to "رکوردهای متنی (TXT)",
            "dns_filter_ns" to "نیم‌سرورها (NS)",
            "dns_filter_cname" to "نام‌های مستعار (CNAME)",
            "dns_filter_soa" to "شروع اقتدار (SOA)",
            "dns_filter_caa" to "مجوز گواهی (CAA)",
            "dns_filter_ptr" to "تفکیک معکوس (PTR)",
            "subnet_calculator" to "محاسبه‌گر ساب‌نت و CIDR",
            "subnet_cidr" to "ماسک شبکه / CIDR",
            "subnet_broadcast" to "آدرس برودکست",
            "subnet_range" to "محدوده هاست‌های قابل استفاده",
            "subnet_total_hosts" to "تعداد هاست‌های فعال",
            "scan_entire_subnet" to "اسکن کامل ساب‌نت شبکه",
            "tcp_ping_mode" to "پینگ پورت TCP (SYN/ACK)",
            "icmp_ping_mode" to "پینگ استاندارد ICMP",
            "ping_port_label" to "پورت TCP"
        ),
        "ru" to mapOf(
            "dashboard" to "Панель управления",
            "tools" to "Инструменты",
            "reports" to "Отчеты",
            "settings" to "Настройки",
            "scan" to "СКАНИРОВАТЬ",
            "stop" to "СТОП",
            "go" to "ПУСК",
            "target" to "Целевой IP / Домен",
            "advanced" to "Расширенные параметры",
            "active_services" to "Активные службы",
            "security_score" to "Оценка безопасности",
            "no_services" to "Службы не найдены",
            "language" to "Язык и регион",
            "theme" to "Внешний вид",
            "accent" to "Акцентный цвет",
            "dark" to "Темная тема",
            "light" to "Светлая тема",
            "internal_ip" to "Внутренний IP",
            "public_ip" to "Публичный IP",
            "interface" to "Сетевой адаптер",
            "refresh" to "Обновить",
            "no_reports" to "Отчеты сканирования не найдены",
            "security_trend" to "Динамика безопасности",
            "global_export_format" to "ФОРМАТ ЭКСПОРТА",
            "format_markdown" to "Markdown (.md)",
            "format_csv" to "Таблица CSV (.csv)",
            "format_json" to "Схема JSON (.json)",
            "scan_report_deleted" to "Отчет сканирования удален",
            "all_reports_cleared" to "Все отчеты сканирования очищены",
            "saved_to" to "Сохранено в",
            "download_failed" to "Ошибка загрузки",
            "share_failed" to "Ошибка отправки",
            "failed_delete_record" to "Не удалось удалить отчет",
            "failed_clear_history" to "Не удалось очистить историю",
            "failed_load_records" to "Не удалось загрузить отчеты",
            "report_copied_clipboard" to "Отчет скопирован в буфер обмена",
            "no_output_to_copy" to "Нет данных для копирования",
            "touch_emulation_active" to "Сенсорный режим",
            "clear_history_title" to "Очистить историю?",
            "clear_history_desc" to "Удалить все записи сканирования навсегда?",
            "clear_all" to "УДАЛИТЬ ВСЕ",
            "cancel" to "ОТМЕНА",
            "not_enough_data" to "НЕДОСТАТОЧНО ДАННЫХ",
            "about" to "О программе",
            "support" to "Поддержка",
            "feedback" to "Обратная связь",
            "engine_configuration" to "КОНФИГУРАЦИЯ ДВИЖКА",
            "engine_config" to "Настройки движка",
            "delete" to "Удалить",
            "scan_protocol" to "Протокол сканирования",
            "parallel_threads" to "Параллельные потоки",
            "connections" to "подключений",
            "banner_grabbing" to "Захват баннеров",
            "full_port_scan" to "Полное сканирование (1-65535)",
            "multi_protocol" to "Мультипротокол (TCP/UDP)",
            "stealth_mode" to "Скрытный режим (Stealth)",
            "device_environment" to "ОКРУЖЕНИЕ УСТРОЙСТВА",
            "connection" to "Подключение",
            "wifi" to "Wi-Fi",
            "wired" to "Проводное (Ethernet)",
            "adapter" to "Сетевой адаптер",
            "tactical_icmp_output" to "ТАКТИЧЕСКИЙ ВЫВОД ICMP",
            "querying" to "ОПРОС...",
            "engine_ready" to "Движок готов...",
            "dns_resolution_records" to "ЗАПИСИ РАЗРЕШЕНИЯ DNS",
            "awaiting_dns" to "Ожидание разрешения целевого узла...",
            "whois_authority_data" to "ДАННЫЕ РЕГИСТРАТОРА WHOIS",
            "ready_whois" to "Готов к запросу WHOIS...",
            "copy_whois" to "Копировать WHOIS",
            "engine_running" to "СКАНИРОВАНИЕ АКТИВНО",
            "ready" to "ГОТОВ",
            "live_engine_logs" to "ЖУРНАЛ СОБЫТИЙ ДВИЖКА",
            "waiting_engine_activity" to "Ожидание активности движка...",
            "found" to "ОБНАРУЖЕНО",
            "scanning_network" to "СКАНИРОВАНИЕ СЕТИ...",
            "threats_detected" to "Обнаружены угрозы",
            "device_profile" to "Профиль устройства",
            "firewall_perimeter" to "Периметр сети",
            "socket_timeout" to "Тайм-аут сокета",
            "ms" to "мс",
            "port_range" to "Диапазон портов",
            "top_100" to "Топ 100",
            "standard_ports" to "1-1024 (Стандарт)",
            "web_ports" to "Веб-порты",
            "custom_range" to "Пользовательский",
            "start_port" to "Начальный порт",
            "end_port" to "Конечный порт",
            "search_reports" to "Фильтр по цели или устройству...",
            "no_matching_reports" to "Подходящие отчеты не найдены",
            "copy_details" to "Копировать детали",
            "copied" to "Скопировано!",
            "close" to "Закрыть",
            "search_ports_placeholder" to "Поиск порта, службы или баннера...",
            "filter_all" to "Все",
            "filter_threats" to "Угрозы / Риск",
            "filter_web" to "Веб",
            "filter_db" to "Базы данных",
            "filter_remote" to "Удаленный доступ",
            "filter_banner" to "С баннером",
            "filter_industrial" to "Промышленный / IoT",
            "filter_safe" to "Безопасные",
            "filter_infra" to "Инфраструктура",
            "filter_identified" to "Опознанные службы",
            "filter_generic" to "Общие / Рефлексивные",
            "filter_system_ports" to "Системные (1-1023)",
            "filter_registered_ports" to "Пользовательские (1024+)",
            "no_ports_found" to "Порты не соответствуют критериям поиска",
            "clear_filter" to "Сбросить фильтр",
            "copy_all_logs" to "Копировать все логи",
            "clear_logs" to "Очистить логи",
            "logs_count" to "Логи",
            "open_ports_count" to "Открытые порты",
            "high_risk" to "Критический / Высокий риск",
            "secure" to "Безопасно",
            "warning" to "Умеренный риск",
            "packets_tx" to "Отправлено",
            "packets_rx" to "Получено",
            "packet_loss" to "Потеря пакетов",
            "avg_latency" to "Средняя задержка",
            "copy_curl" to "Копировать cURL",
            "copy_url" to "Копировать URL",
            "engine_standby" to "Движок в режиме ожидания",
            "engine_active" to "Активное сканирование",
            "system_info" to "Система и архитектура",
            "runtime_arch" to "Среда выполнения",
            "quick_localhost" to "Локальный узел (127.0.0.1)",
            "valid_target_ip" to "Целевой IPv4",
            "valid_target_domain" to "Целевой домен",
            "whois_summary" to "Сводка WHOIS",
            "registrar" to "Регистратор",
            "created_date" to "Дата создания",
            "expiry_date" to "Дата истечения",
            "dns_records_count" to "Разрешенные записи",
            "quick_targets" to "Быстрые цели",
            "port_presets" to "Профили портов",
            "top_20" to "Топ 20",
            "top_1000" to "Топ 1000",
            "all_65k" to "Все 65 535",
            "web_services" to "Веб (80, 443)",
            "db_services" to "Базы данных",
            "remote_iot" to "Удаленный доступ и IoT",
            "logs_tab" to "Живой журнал",
            "services_tab" to "Найденные службы",
            "report_detail_title" to "Детали отчета безопасности",
            "executive_summary" to "Сводный отчет",
            "discovered_ports" to "Обнаруженные порты",
            "risk_analysis" to "Анализ рисков",
            "firewall_status" to "Состояние брандмауэра",
            "anomalies_detected" to "Аномалии сети",
            "min_latency" to "Мин. задержка",
            "max_latency" to "Макс. задержка",
            "jitter" to "Джиттер",
            "scan_subnet" to "Сканировать подсеть",
            "threat_score" to "Индекс угроз",
            "grade" to "Класс защиты",
            "copied_to_clipboard" to "Скопировано в буфер обмена",
            "app_lifecycle" to "Жизненный цикл и обслуживание приложения",
            "check_updates" to "Проверить обновления",
            "up_to_date" to "Установлена последняя версия PortX",
            "repair_app" to "Восстановить приложение",
            "repair_desc" to "Сброс пула сокетов и очистка кэша базы данных",
            "uninstall_app" to "Удалить PortX",
            "uninstall_confirm_title" to "Удалить PortX?",
            "uninstall_confirm_desc" to "Будет запущен деинсталлятор Windows для полного удаления PortX из системы.",
            "launch_uninstaller" to "Запустить деинсталлятор",
            "placeholder_dns" to "Домен (напр. google.com)",
            "placeholder_whois" to "Домен (напр. wikipedia.org)",
            "ping_gateway" to "Пинг шлюза",
            "gateway_label" to "Шлюз",
            "firewall_open" to "Открытый периметр",
            "firewall_hardened" to "Усиленный периметр",
            "firewall_standard" to "Стандартный профиль сети",
            "firewall_filtered" to "Брандмауэр активен",
            "load_more_ports" to "Загрузить еще порты",
            "showing_ports_count" to "Отображается {shown} из {total} открытых портов",
            "no_open_ports" to "Открытых портов не обнаружено. Периметр полностью защищен.",
            "search_ports_in_report" to "Фильтр портов в отчете...",
            "device_mode" to "Режим эмуляции устройства",
            "device_responsive" to "Адаптивный",
            "rotate_device" to "Повернуть экран",
            "snap_window" to "Подогнать окно под устройство",
            "device_frame" to "Рамка устройства",
            "os_fingerprint" to "Отпечаток ОС",
            "download_report" to "Скачать",
            "share_report" to "Поделиться",
            "detected_banner" to "ОБНАРУЖЕННЫЙ БАННЕР / СИГНАТУРА СЛУЖБЫ",
            "security_advisory" to "РЕКОМЕНДАЦИИ ПО БЕЗОПАСНОСТИ",
            "tcp_listening" to "ПРОСЛУШИВАЕТСЯ TCP",
            "port_open" to "ОТКРЫТ",
            "export_report" to "Экспорт и сохранение",
            "export_modal_title" to "Экспорт отчета сканирования",
            "export_format_label" to "Формат экспорта",
            "preview" to "Предпросмотр экспорта",
            "save_as_file" to "Сохранить как...",
            "quick_save_downloads" to "Сохранить в Загрузки",
            "share_file_native" to "Системная отправка",
            "copy_content" to "Копировать содержимое",
            "trend_improved" to "Безопасность повышается",
            "trend_declined" to "Безопасность снижается",
            "trend_stable" to "Уровень стабилен",
            "peak_score" to "Максимум",
            "min_score" to "Минимум",
            "avg_score" to "Среднее",
            "latest_score" to "Последний",
            "click_to_view" to "Нажмите на точку для просмотра деталей",
            "trend_all" to "Все сканирования",
            "trend_last_10" to "Последние 10",
            "trend_last_25" to "Последние 25",
            "trend_critical" to "Критические (<50%)",
            "file_size" to "Размер",
            "lines_count" to "Строки",
            "core_engine" to "Ядро движка",
            "core_engine_val" to "Асинхронные сокеты NIO",
            "threat_intel" to "Анализ угроз и уязвимостей",
            "threat_intel_val" to "База NVD / CVE встроена v2026.1",
            "local_persistence" to "Локальное хранилище",
            "local_persistence_val" to "Шифрованная SQLite Local-First",
            "app_footer_build" to "Комплекс кибербезопасности PortX Pro v5.3.0 • Релизная сборка",
            "engine_online" to "ДВИЖОК ОНЛАЙН",
            "engine_scanning_badge" to "СКАНИРОВАНИЕ",
            "security_suite_sub" to "КОМПЛЕКС КИБЕРБЕЗОПАСНОСТИ v5.2",
            "engine_socket_sub" to "Асинхронные сокеты NIO • TCP/UDP",
            "toggle_theme" to "Переключить тему",
            "quick_target_localhost" to "Локальный",
            "quick_target_gateway" to "Шлюз",
            "quick_target_nmap" to "Сервер Nmap",
            "tool_local" to "СЕТЬ",
            "tool_ping" to "ПИНГ",
            "tool_dns" to "DNS",
            "tool_whois" to "WHOIS",
            "verified_registrar" to "ПРОВЕРЕННЫЙ РЕГИСТРАТОР",
            "badge_local" to "ЛОКАЛЬНО",
            "ping_action" to "Пинг",
            "copy_line" to "Копировать строку",
            "copy" to "Копировать",
            "format_markdown" to "Markdown (.md)",
            "format_csv" to "Таблица CSV (.csv)",
            "format_json" to "Схема JSON (.json)",
            "clear_all_reports" to "Очистить все отчеты",
            "port_detail_port" to "Порт",
            "port_detail_title" to "Название",
            "port_detail_target" to "Цель",
            "port_detail_status" to "Статус",
            "port_detail_banner" to "Баннер",
            "port_detail_risk" to "Уровень риска",
            "port_detail_advisory" to "Рекомендация",
            "err_enter_ip" to "Пожалуйста, введите IP-адрес или имя хоста",
            "err_invalid_target" to "Неверный формат цели (напр. 8.8.8.8 или example.com)",
            "err_port_range" to "Диапазон должен быть от 1 до 65535",
            "err_numeric_range" to "Недопустимый числовой диапазон портов",
            "err_enter_dns" to "Пожалуйста, введите домен для разрешения",
            "err_enter_whois" to "Пожалуйста, введите домен (напр. google.com)",
            "err_whois_unreachable" to "Служба WHOIS недоступна.",
            "err_dns_unreachable" to "Записи DNS для цели не найдены. Проверьте подключение.",
            "err_engine_failure" to "Произошла ошибка движка во время сетевой операции.",
            "expand" to "Развернуть",
            "collapse" to "Свернуть",
            "port_category" to "Категория",
            "port_rfc" to "Стандарт и RFC",
            "port_tier" to "Уровень порта",
            "port_encryption" to "Шифрование",
            "attack_vectors" to "Векторы атак",
            "common_cves" to "Анализ угроз и CVE",
            "hardening_guide" to "Рекомендации по защите",
            "waf_anomaly_title" to "Аномалия WAF / SYN-Proxy",
            "waf_anomaly_desc" to "Периметр цели синтетически подтверждает закрытые порты. Отраженные порты отфильтрованы из оценки безопасности.",
            "privileged_port" to "Системный / Привилегированный (0-1023)",
            "registered_port" to "Зарегистрированный (1024-49151)",
            "dynamic_port" to "Динамический / Частный (49152-65535)",
            "cat_infra" to "Сетевая инфраструктура",
            "cat_web" to "Веб-службы и API",
            "cat_remote" to "Удаленное администрирование",
            "cat_database" to "Базы данных и кэш",
            "cat_files" to "Файловые службы и общий доступ",
            "cat_mail" to "Почта и сообщения",
            "cat_industrial" to "Промышленные АСУ ТП и SCADA",
            "cat_cloud" to "Облачные платформы и контейнеры",
            "cat_iot" to "IoT и микроконтроллеры",
            "cat_general" to "Общая сетевая служба",
            "enc_tls" to "Шифрование TLS / SSL",
            "enc_ssh" to "Шифрованный поток SSH",
            "enc_cleartext" to "Открытый текст (Без шифрования)",
            "enc_binary" to "Бинарный поток RPC",
            "enc_kerberos" to "Подпись Kerberos / NTLM",
            "dns_server_used" to "DNS-сервер",
            "dns_response_time" to "Время ответа",
            "dns_records_count" to "Записи",
            "dns_view_cards" to "Карточки",
            "dns_view_raw" to "Dig / Журнал",
            "dns_dnssec_valid" to "DNSSEC подтвержден",
            "dns_priority" to "Приоритет",
            "dns_ttl" to "TTL",
            "dns_filter_all" to "Все",
            "dns_filter_ip" to "A / AAAA",
            "dns_filter_mx" to "MX (Почта)",
            "dns_filter_txt" to "TXT",
            "dns_filter_ns" to "NS",
            "dns_filter_cname" to "CNAME",
            "dns_filter_soa" to "SOA",
            "dns_filter_caa" to "CAA",
            "dns_filter_ptr" to "PTR",
            "subnet_calculator" to "Калькулятор подсети и CIDR",
            "subnet_cidr" to "Маска подсети / CIDR",
            "subnet_broadcast" to "Широковещательный адрес",
            "subnet_range" to "Диапазон доступных хостов",
            "subnet_total_hosts" to "Доступных хостов",
            "scan_entire_subnet" to "Сканировать всю подсеть",
            "tcp_ping_mode" to "TCP Ping (SYN/ACK)",
            "icmp_ping_mode" to "Стандартный ICMP",
            "ping_port_label" to "Порт TCP"
        )
    )

    fun get(key: String, lang: String): String {
        return strings[lang]?.get(key) ?: strings["en"]?.get(key) ?: key
    }

    /**
     * Localizes live engine daemon logs for display according to active app language.
     * Provides Persian translations with Persian digits in FA mode, Russian translations in RU mode,
     * and preserves standard raw technical output in EN mode.
     */
    fun formatLog(rawLog: String, lang: String): String {
        if (lang != "fa" && lang != "ru") return rawLog

        val trimmed = rawLog.trim()

        // 1. Target validated: <target>
        if (trimmed.startsWith("Target validated:", ignoreCase = true)) {
            val target = trimmed.substringAfter(":").trim()
            return when (lang) {
                "fa" -> "هدف اعتبارسنجی شد: $target"
                "ru" -> "Цель проверена: $target"
                else -> rawLog
            }
        }

        // 2. Probing network interface...
        if (trimmed.equals("Probing network interface...", ignoreCase = true)) {
            return when (lang) {
                "fa" -> "در حال بررسی رابط شبکه..."
                "ru" -> "Проверка сетевого интерфейса..."
                else -> rawLog
            }
        }

        // 3. External connectivity confirmed.
        if (trimmed.equals("External connectivity confirmed.", ignoreCase = true)) {
            return when (lang) {
                "fa" -> "اتصال به اینترنت و شبکه خارجی تأیید شد."
                "ru" -> "Внешнее сетевое подключение подтверждено."
                else -> rawLog
            }
        }

        // 4. Proceeding with direct target route...
        if (trimmed.equals("Proceeding with direct target route...", ignoreCase = true)) {
            return when (lang) {
                "fa" -> "ادامه با مسیر مستقیم به سمت هدف..."
                "ru" -> "Переход к прямому маршруту к цели..."
                else -> rawLog
            }
        }

        // 5. Local interface active.
        if (trimmed.equals("Local interface active.", ignoreCase = true)) {
            return when (lang) {
                "fa" -> "رابط شبکه محلی فعال است."
                "ru" -> "Локальный сетевой интерфейс активен."
                else -> rawLog
            }
        }

        // 6. Engine v5.3.0 initializing... / Engine ... initializing...
        if (trimmed.contains("Engine", ignoreCase = true) && trimmed.contains("initializing", ignoreCase = true)) {
            val version = trimmed.substringAfter("Engine", "").substringBefore("initializing").trim()
            val verText = if (version.isNotBlank()) " $version" else ""
            return when (lang) {
                "fa" -> "در حال مقداردهی اولیه موتور$verText..."
                "ru" -> "Инициализация движка$verText..."
                else -> rawLog
            }
        }

        // 7. Full port scan mode [1-65535] active
        if (trimmed.contains("Full port scan mode", ignoreCase = true)) {
            return when (lang) {
                "fa" -> "حالت اسکن کامل تمام پورت‌ها [۱-۶۵۵۳۵] فعال شد."
                "ru" -> "Режим полного сканирования всех портов [1-65535] активен."
                else -> rawLog
            }
        }

        // 8. Operationalizing <scanType> scan...
        if (trimmed.startsWith("Operationalizing", ignoreCase = true)) {
            val type = trimmed.substringAfter("Operationalizing").substringBefore("scan").trim()
            return when (lang) {
                "fa" -> "راه‌اندازی و اجرای اسکن $type..."
                "ru" -> "Запуск и выполнение сканирования $type..."
                else -> rawLog
            }
        }

        // 9. Scan stopped by user.
        if (trimmed.equals("Scan stopped by user.", ignoreCase = true)) {
            return when (lang) {
                "fa" -> "اسکن توسط کاربر متوقف گردید."
                "ru" -> "Сканирование остановлено пользователем."
                else -> rawLog
            }
        }

        // 10. Scan completed: <count> open ports found on <target> (Score: <score>%)
        if (trimmed.startsWith("Scan completed:", ignoreCase = true)) {
            try {
                val countStr = trimmed.substringAfter("Scan completed:").substringBefore("open ports").trim()
                val targetStr = trimmed.substringAfter("found on").substringBefore("(Score:").trim()
                val scoreStr = trimmed.substringAfter("(Score:").substringBefore("%)").trim()

                val countInt = countStr.toIntOrNull() ?: 0
                val scoreInt = scoreStr.toIntOrNull() ?: 0

                return when (lang) {
                    "fa" -> {
                        val countFa = DateFormatter.toPersianDigits(countInt.toString())
                        val scoreFa = DateFormatter.toPersianDigits(scoreInt.toString())
                        "اسکن پایان یافت: $countFa پورت باز در $targetStr یافت شد (امتیاز امنیت: $scoreFa٪)"
                    }
                    "ru" -> "Сканирование завершено: найдено $countInt открытых портов на $targetStr (Оценка: $scoreInt%)"
                    else -> rawLog
                }
            } catch (_: Exception) {
                return when (lang) {
                    "fa" -> "اسکن با موفقیت به پایان رسید."
                    "ru" -> "Сканирование успешно завершено."
                    else -> rawLog
                }
            }
        }

        // 11. Engine error: <error>
        if (trimmed.startsWith("Engine error:", ignoreCase = true)) {
            val err = trimmed.substringAfter("Engine error:").trim()
            val localizedErr = get(err, lang)
            return when (lang) {
                "fa" -> "خطای موتور اسکن: $localizedErr"
                "ru" -> "Ошибка движка сканирования: $localizedErr"
                else -> "Engine error: $localizedErr"
            }
        }

        return get(rawLog, lang)
    }
}
