package com.mrcoder20.portx.domain

import androidx.compose.runtime.Composable

enum class Language(val code: String, val label: String) {
    EN("en", "English"),
    FA("fa", "فارسی"),
    ES("es", "Español"),
    FR("fr", "Français"),
    DE("de", "Deutsch"),
    RU("ru", "Русский"),
    ZH("zh", "中文"),
    JA("ja", "日本語"),
    AR("ar", "العربية"),
    HI("hi", "हिन्दी")
}

object LocalizedStrings {
    private val strings = mapOf(
        "en" to mapOf(
            "dashboard" to "Dashboard",
            "tools" to "Tools",
            "reports" to "Reports",
            "settings" to "Settings",
            "scan" to "SCAN",
            "stop" to "STOP",
            "go" to "GO",
            "target" to "Target IP / Domain",
            "advanced" to "Advanced Parameters",
            "active_services" to "Active Services",
            "security_score" to "Security Score",
            "no_services" to "No Services Found",
            "language" to "Language & Region",
            "theme" to "Appearance",
            "accent" to "Accent Color",
            "dark" to "Dark Mode",
            "light" to "Light Mode",
            "internal_ip" to "Internal IP",
            "public_ip" to "Public IP",
            "interface" to "Network Adapter",
            "refresh" to "Refresh",
            "no_reports" to "No Scan Reports Found",
            "security_trend" to "Security Trend",
            "global_export_format" to "GLOBAL EXPORT FORMAT",
            "clear_history_title" to "Clear History?",
            "clear_history_desc" to "Permanently delete all scan records?",
            "clear_all" to "CLEAR ALL",
            "cancel" to "CANCEL",
            "not_enough_data" to "NOT ENOUGH DATA",
            "about" to "About",
            "support" to "Support",
            "feedback" to "Feedback",
            "engine_configuration" to "ENGINE CONFIGURATION",
            "parallel_threads" to "Parallel Threads",
            "connections" to "connections",
            "banner_grabbing" to "Banner Grabbing",
            "full_port_scan" to "Full Port Scan",
            "multi_protocol" to "Multi-Protocol",
            "stealth_mode" to "Stealth Mode",
            "device_environment" to "DEVICE ENVIRONMENT",
            "connection" to "Connection",
            "wifi" to "Wi-Fi",
            "wired" to "Wired",
            "adapter" to "Adapter",
            "tactical_icmp_output" to "TACTICAL ICMP OUTPUT",
            "querying" to "QUERYING...",
            "engine_ready" to "Engine ready...",
            "dns_resolution_records" to "DNS RESOLUTION RECORDS",
            "awaiting_dns" to "Awaiting target resolution...",
            "whois_authority_data" to "WHOIS AUTHORITY DATA",
            "ready_whois" to "Ready to query WHOIS...",
            "copy_whois" to "Copy WHOIS",
            "engine_running" to "ENGINE RUNNING",
            "ready" to "READY",
            "live_engine_logs" to "LIVE ENGINE LOGS",
            "waiting_engine_activity" to "Waiting for engine activity...",
            "found" to "FOUND",
            "scanning_network" to "SCANNING NETWORK...",
            "threats_detected" to "Threats Detected",
            "device_profile" to "Device Profile",
            "firewall_perimeter" to "Perimeter",
            "socket_timeout" to "Socket Timeout",
            "ms" to "ms",
            "port_range" to "Port Range",
            "top_100" to "Top 100",
            "standard_ports" to "1-1024",
            "web_ports" to "Web Ports",
            "custom_range" to "Custom",
            "start_port" to "Start Port",
            "end_port" to "End Port",
            "search_reports" to "Filter by target or device...",
            "no_matching_reports" to "No matching reports found",
            "copy_details" to "Copy Details",
            "copied" to "Copied!",
            "close" to "Close",
            "search_ports_placeholder" to "Search port, service, or banner...",
            "filter_all" to "All",
            "filter_threats" to "Threats",
            "filter_web" to "Web",
            "filter_db" to "Database",
            "filter_remote" to "Remote/Admin",
            "no_ports_found" to "No ports match search criteria",
            "clear_filter" to "Clear Filter",
            "copy_all_logs" to "Copy All Logs",
            "clear_logs" to "Clear Logs",
            "logs_count" to "Logs",
            "open_ports_count" to "Open Ports",
            "high_risk" to "Critical / High Risk",
            "secure" to "Secure",
            "warning" to "Moderate Risk",
            "packets_tx" to "Sent",
            "packets_rx" to "Received",
            "packet_loss" to "Packet Loss",
            "avg_latency" to "Avg Latency",
            "copy_curl" to "Copy cURL",
            "copy_url" to "Copy URL",
            "engine_standby" to "Engine Standby",
            "engine_active" to "Scanning Active",
            "scan_presets" to "Performance Presets",
            "preset_fast" to "Turbo (500 Conn)",
            "preset_balanced" to "Balanced (100 Conn)",
            "preset_deep" to "Stealth (20 Conn)",
            "system_info" to "System & Architecture",
            "runtime_arch" to "Desktop Runtime",
            "quick_localhost" to "Localhost (127.0.0.1)",
            "valid_target_ip" to "IPv4 Target",
            "valid_target_domain" to "Domain Target",
            "whois_summary" to "Domain Summary",
            "registrar" to "Registrar",
            "created_date" to "Created Date",
            "expiry_date" to "Expiry Date",
            "dns_records_count" to "Resolved Records",
            "quick_targets" to "Quick Targets",
            "port_presets" to "Port Profiles",
            "top_20" to "Top 20",
            "top_1000" to "Top 1000",
            "all_65k" to "All 65,535",
            "web_services" to "Web (80, 443)",
            "db_services" to "Database",
            "remote_iot" to "Remote & IoT",
            "logs_tab" to "Live Logs",
            "services_tab" to "Discovered Services",
            "report_detail_title" to "Scan Report Details",
            "executive_summary" to "Executive Summary",
            "discovered_ports" to "Discovered Ports",
            "risk_analysis" to "Risk Analysis",
            "firewall_status" to "Firewall State",
            "anomalies_detected" to "Anomalies",
            "close" to "Close",
            "min_latency" to "Min Latency",
            "max_latency" to "Max Latency",
            "jitter" to "Jitter",
            "scan_subnet" to "Scan Subnet",
            "threat_score" to "Threat Score",
            "grade" to "Grade",
            "copied_to_clipboard" to "Copied to clipboard",
            "app_lifecycle" to "Application Lifecycle & Maintenance",
            "check_updates" to "Check for Updates",
            "up_to_date" to "PortX is up to date",
            "repair_app" to "Repair Installation",
            "repair_desc" to "Reset socket pool and database cache",
            "uninstall_app" to "Uninstall PortX",
            "uninstall_confirm_title" to "Uninstall PortX?",
            "uninstall_confirm_desc" to "This will launch the Windows uninstaller to remove PortX from your system.",
            "launch_uninstaller" to "Launch Uninstaller",
            "placeholder_dns" to "Domain (e.g. google.com)",
            "placeholder_whois" to "Domain (e.g. wikipedia.org)",
            "ping_gateway" to "Ping Gateway",
            "gateway_label" to "Gateway",
            "firewall_open" to "Open Perimeter",
            "firewall_hardened" to "Hardened Perimeter",
            "firewall_standard" to "Standard Network Profile",
            "firewall_filtered" to "Firewall Active",
            "load_more_ports" to "Load More Ports",
            "showing_ports_count" to "Showing {shown} of {total} open ports",
            "no_open_ports" to "No open ports detected. Perimeter is fully sealed.",
            "search_ports_in_report" to "Filter report ports...",
            "device_mode" to "Device Mode",
            "device_responsive" to "Responsive",
            "rotate_device" to "Rotate Screen",
            "snap_window" to "Snap Window to Device",
            "device_frame" to "Device Bezel Frame",
            "os_fingerprint" to "OS Fingerprint",
            "download_report" to "Download",
            "share_report" to "Share",
            "detected_banner" to "DETECTED BANNER / SERVICE SIGNATURE",
            "security_advisory" to "SECURITY ADVISORY & HARDENING",
            "tcp_listening" to "TCP LISTENING",
            "port_open" to "OPEN",
            "export_report" to "Export & Save",
            "export_modal_title" to "Export Scan Report",
            "export_format_label" to "Export Format",
            "preview" to "Live Export Preview",
            "save_as_file" to "Save As...",
            "quick_save_downloads" to "Save to Downloads",
            "share_file_native" to "System Share",
            "copy_content" to "Copy Content",
            "trend_improved" to "Security Improving",
            "trend_declined" to "Security Declining",
            "trend_stable" to "Security Stable",
            "peak_score" to "Peak",
            "min_score" to "Min",
            "avg_score" to "Avg",
            "latest_score" to "Latest",
            "click_to_view" to "Click point to view details",
            "trend_all" to "All Scans",
            "trend_last_10" to "Last 10",
            "trend_last_25" to "Last 25",
            "trend_critical" to "Critical (<50%)",
            "file_size" to "Size",
            "lines_count" to "Lines"
        ),
        "fa" to mapOf(
            "dashboard" to "داشبورد",
            "tools" to "ابزارها",
            "reports" to "گزارش‌ها",
            "settings" to "تنظیمات",
            "scan" to "اسکن",
            "stop" to "توقف",
            "go" to "اجرا",
            "target" to "آی‌پی یا دامنه هدف",
            "advanced" to "تنظیمات پیشرفته",
            "active_services" to "سرویس‌های فعال",
            "security_score" to "امتیاز امنیتی",
            "no_services" to "سرویسی یافت نشد",
            "language" to "زبان و منطقه",
            "theme" to "ظاهر برنامه",
            "accent" to "رنگ اصلی",
            "dark" to "حالت تاریک",
            "light" to "حالت روشن",
            "internal_ip" to "آی‌پی داخلی",
            "public_ip" to "آی‌پی عمومی",
            "interface" to "کارت شبکه",
            "refresh" to "به‌روزرسانی",
            "no_reports" to "گزارش اسکنی یافت نشد",
            "security_trend" to "روند امنیت",
            "global_export_format" to "فرمت خروجی گزارش",
            "clear_history_title" to "پاک‌سازی تاریخچه؟",
            "clear_history_desc" to "تمام سوابق اسکن برای همیشه حذف شوند؟",
            "clear_all" to "حذف همه",
            "cancel" to "انصراف",
            "not_enough_data" to "داده کافی نیست",
            "about" to "درباره ما",
            "support" to "پشتیبانی",
            "feedback" to "بازخورد",
            "engine_configuration" to "پیکربندی موتور اسکن",
            "parallel_threads" to "تعداد کانکشن‌های همزمان",
            "connections" to "اتصال",
            "banner_grabbing" to "دریافت بنر سرویس‌ها",
            "full_port_scan" to "اسکن تمام پورت‌ها (۱-۶۵۵۳۵)",
            "multi_protocol" to "چند پروتکلی (TCP/UDP)",
            "stealth_mode" to "حالت پنهانکار (Stealth)",
            "device_environment" to "اطلاعات کارت شبکه و سیستم",
            "connection" to "نوع اتصال",
            "wifi" to "بی‌سیم (Wi-Fi)",
            "wired" to "کابلی (Ethernet)",
            "adapter" to "کارت شبکه",
            "tactical_icmp_output" to "خروجی بسته‌های پینگ (ICMP)",
            "querying" to "در حال ارسال درخواست...",
            "engine_ready" to "موتور آماده اجرا...",
            "dns_resolution_records" to "رکوردهای تفکیک نام (DNS)",
            "awaiting_dns" to "در انتظار تفکیک دامنه...",
            "whois_authority_data" to "اطلاعات ثبت دامنه (WHOIS)",
            "ready_whois" to "آماده دریافت اطلاعات هویتی دامنه...",
            "copy_whois" to "کپی اطلاعات دامنه",
            "engine_running" to "موتور در حال اسکن",
            "ready" to "آماده",
            "live_engine_logs" to "لاگ زنده وقایع موتور اسکن",
            "waiting_engine_activity" to "در انتظار شروع پردازش...",
            "found" to "مورد شناسایی شد",
            "scanning_network" to "در حال بررسی شبکه...",
            "threats_detected" to "تهدید شناسایی شد",
            "device_profile" to "مشخصات دستگاه",
            "firewall_perimeter" to "محدوده شبکه",
            "socket_timeout" to "مهلت زمانی اتصال",
            "ms" to "میلی‌ثانیه",
            "port_range" to "محدوده پورت‌ها",
            "top_100" to "۱۰۰ پورت پرکاربرد",
            "standard_ports" to "۱ تا ۱۰۲۴ (پیش‌فرض)",
            "web_ports" to "پورت‌های وب",
            "custom_range" to "سفارشی",
            "start_port" to "پورت شروع",
            "end_port" to "پورت پایان",
            "search_reports" to "جستجو بر اساس هدف یا دستگاه...",
            "no_matching_reports" to "گزارشی مطابق جستجو یافت نشد",
            "copy_details" to "کپی جزئیات",
            "copied" to "کپی شد!",
            "close" to "بستن",
            "search_ports_placeholder" to "جستجوی پورت، سرویس یا بنر...",
            "filter_all" to "همه",
            "filter_threats" to "پرخطر / تهدید",
            "filter_web" to "وب (Web)",
            "filter_db" to "پایگاه‌داده (DB)",
            "filter_remote" to "مدیریتی (Remote)",
            "no_ports_found" to "هیچ پورتی مطابق با فیلتر یافت نشد",
            "clear_filter" to "پاک‌سازی فیلتر",
            "copy_all_logs" to "کپی همه لاگ‌ها",
            "clear_logs" to "پاک‌سازی لاگ‌ها",
            "logs_count" to "لاگ وقایع",
            "open_ports_count" to "پورت باز",
            "high_risk" to "پرخطر / بحرانی",
            "secure" to "امن",
            "warning" to "ریسک متوسط",
            "packets_tx" to "ارسال",
            "packets_rx" to "دریافت",
            "packet_loss" to "افت بسته",
            "avg_latency" to "میانگین تاخیر",
            "copy_curl" to "کپی دستور cURL",
            "copy_url" to "کپی آدرس",
            "engine_standby" to "موتور آماده به کار",
            "engine_active" to "اسکن فعال",
            "scan_presets" to "پروفایل‌های کارایی اسکن",
            "preset_fast" to "توربو (۵۰۰ اتصال)",
            "preset_balanced" to "متعادل (۱۰۰ اتصال)",
            "preset_deep" to "پنهانکار (۲۰ اتصال)",
            "system_info" to "مشخصات سیستم و معماری",
            "runtime_arch" to "محیط اجرای دسکتاپ",
            "quick_localhost" to "لوکال‌هاست (127.0.0.1)",
            "valid_target_ip" to "آی‌پی IPv4",
            "valid_target_domain" to "دامنه معتبر",
            "whois_summary" to "خلاصه هویتی دامنه",
            "registrar" to "ثبت‌کننده",
            "created_date" to "تاریخ ایجاد",
            "expiry_date" to "تاریخ انقضا",
            "dns_records_count" to "رکوردهای شناسایی‌شده",
            "quick_targets" to "اهداف سریع",
            "port_presets" to "پروفایل‌های پورت",
            "top_20" to "۲۰ پورت برتر",
            "top_1000" to "۱۰۰۰ پورت استاندارد",
            "all_65k" to "تمام ۶۵٬۵۳۵ پورت",
            "web_services" to "وب (80, 443)",
            "db_services" to "پایگاه داده (DB)",
            "remote_iot" to "دسترسی راه دور و اینترنت اشیا",
            "logs_tab" to "لاگ‌های زنده",
            "services_tab" to "سرویس‌های کشف‌شده",
            "report_detail_title" to "جزئیات گزارش امنیتی",
            "executive_summary" to "خلاصه مدیریتی",
            "discovered_ports" to "پورت‌های شناسایی‌شده",
            "risk_analysis" to "تحلیل سطح مخاطره",
            "firewall_status" to "وضعیت دیواره آتش",
            "anomalies_detected" to "ناهنجاری‌های شبکه",
            "close" to "بستن",
            "min_latency" to "حداقل تاخیر",
            "max_latency" to "حداکثر تاخیر",
            "jitter" to "نوسان تاخیر",
            "scan_subnet" to "اسکن زیرشبکه محلی",
            "threat_score" to "شاخص ریسک",
            "grade" to "رتبه امنیتی",
            "copied_to_clipboard" to "در حافظه موقت کپی شد",
            "app_lifecycle" to "مدیریت چرخه حیات و نگهداری برنامه",
            "check_updates" to "بررسی به‌روزرسانی",
            "up_to_date" to "برنامه به‌روز است",
            "repair_app" to "تعمیر و بازیابی برنامه",
            "repair_desc" to "بازنشانی حافظه موقت و اعتبارسنجی پایگاه‌داده",
            "uninstall_app" to "حذف کامل برنامه (Uninstall)",
            "uninstall_confirm_title" to "آیا از حذف PortX اطمینان دارید؟",
            "uninstall_confirm_desc" to "این فرآیند دستیار رسمی حذف ویندوز را برای پاک‌سازی PortX از سیستم اجرا می‌کند.",
            "launch_uninstaller" to "اجرای حذف‌کننده ویندوز",
            "placeholder_dns" to "دامنه (مثال: google.com)",
            "placeholder_whois" to "دامنه (مثال: wikipedia.org)",
            "ping_gateway" to "پینگ گیت‌وی",
            "gateway_label" to "گیت‌وی",
            "firewall_open" to "محدوده باز شبکه",
            "firewall_hardened" to "محدوده امن شبکه",
            "firewall_standard" to "پروفایل شبکه استاندارد",
            "firewall_filtered" to "دیواره آتش فعال",
            "load_more_ports" to "بارگذاری پورت‌های بیشتر",
            "showing_ports_count" to "نمایش {shown} از {total} پورت باز",
            "no_open_ports" to "هیچ پورت بازی یافت نشد. محدوده کاملاً امن و مسدود است.",
            "search_ports_in_report" to "فیلتر و جستجوی پورت‌های گزارش...",
            "device_mode" to "شبیه‌ساز دستگاه",
            "device_responsive" to "ریسپانسیو خودکار",
            "rotate_device" to "چرخش صفحه",
            "snap_window" to "تطبیق ابعاد پنجره با دستگاه",
            "device_frame" to "قاب فیزیکی دستگاه",
            "download_report" to "دریافت گزارش",
            "share_report" to "اشتراک‌گذاری",
            "detected_banner" to "امضای سرویس و بنر کشف‌شده",
            "security_advisory" to "توصیه‌های امنیتی و مقاوم‌سازی",
            "tcp_listening" to "در حال شنود (TCP)",
            "port_open" to "پورت باز",
            "export_report" to "خروجی و ذخیره گزارش",
            "export_modal_title" to "خروجی و ذخیره گزارش اسکن",
            "export_format_label" to "فرمت خروجی",
            "preview" to "پیش‌نمایش زنده خروجی",
            "save_as_file" to "ذخیره در مسیر دلخواه...",
            "quick_save_downloads" to "ذخیره در پوشه دانلودها",
            "share_file_native" to "اشتراک‌گذاری سیستمی",
            "copy_content" to "کپی در حافظه",
            "trend_improved" to "بهبود سطح امنیت",
            "trend_declined" to "کاهش سطح امنیت",
            "trend_stable" to "وضعیت امنیتی پایدار",
            "peak_score" to "بیشترین",
            "min_score" to "کمترین",
            "avg_score" to "میانگین",
            "latest_score" to "آخرین",
            "click_to_view" to "کلیک روی نقطه برای مشاهده جزئیات",
            "trend_all" to "همه اسکن‌ها",
            "trend_last_10" to "۱۰ اسکن اخیر",
            "trend_last_25" to "۲۵ اسکن اخیر",
            "trend_critical" to "فقط پرخطرها (<۵۰٪)",
            "file_size" to "حجم",
            "lines_count" to "خط"
        ),
        "ar" to mapOf(
            "dashboard" to "لوحة القيادة",
            "tools" to "الأدوات",
            "reports" to "التقارير",
            "settings" to "الإعدادات",
            "scan" to "مسح",
            "stop" to "إيقاف",
            "go" to "انطلاق",
            "target" to "عنوان IP / النطاق المستهدف",
            "advanced" to "الإعدادات المتقدمة",
            "active_services" to "الخدمات النشطة",
            "security_score" to "درجة الأمان",
            "no_services" to "لم يتم العثور على خدمات",
            "language" to "اللغة والمنطقة",
            "theme" to "المظهر",
            "accent" to "اللون المميز",
            "dark" to "الوضع الداكن",
            "light" to "الوضع الفاتح",
            "internal_ip" to "عنوان IP الداخلي",
            "public_ip" to "عنوان IP العام",
            "interface" to "محول الشبكة",
            "refresh" to "تحديث",
            "threats_detected" to "التهديدات المكتشفة",
            "device_profile" to "ملف تعريف الجهاز",
            "firewall_perimeter" to "محيط الجدار الناري",
            "socket_timeout" to "مهلة الاتصال",
            "ms" to "مللي ثانية",
            "port_range" to "نطاق المنافذ",
            "top_100" to "أفضل 100 منفذ",
            "standard_ports" to "1-1024 قياسي",
            "web_ports" to "منافذ الويب",
            "custom_range" to "مخصص",
            "start_port" to "منفذ البدء",
            "end_port" to "منفذ النهاية",
            "search_reports" to "تصفية حسب الهدف أو الجهاز...",
            "no_matching_reports" to "لم يتم العثور على تقارير مطابقة",
            "global_export_format" to "تنسيق التصدير العالمي",
            "clear_history_title" to "مسح السجل؟",
            "clear_history_desc" to "حذف جميع سجلات الفحص نهائياً؟",
            "clear_all" to "مسح الكل",
            "cancel" to "إلغاء",
            "about" to "حول البرنامج",
            "support" to "الدعم الفني",
            "feedback" to "الملاحظات",
            "banner_grabbing" to "التقاط اللافتات",
            "full_port_scan" to "فحص كامل للمنافذ",
            "multi_protocol" to "متعدد البروتوكولات",
            "not_enough_data" to "بيانات غير كافية",
            "copy_all_logs" to "نسخ جميع السجلات",
            "clear_logs" to "مسح السجلات",
            "logs_count" to "سجلات الأحداث",
            "open_ports_count" to "منافذ مفتوحة",
            "high_risk" to "خطر مرتفع",
            "secure" to "آمن",
            "warning" to "خطر متوسط",
            "packets_tx" to "إرسال",
            "packets_rx" to "استلام",
            "packet_loss" to "فقدان الحزم",
            "avg_latency" to "متوسط التأخير",
            "copy_curl" to "نسخ cURL",
            "copy_url" to "نسخ الرابط",
            "engine_standby" to "المحرك جاهز",
            "engine_active" to "المسح نشط",
            "scan_presets" to "إعدادات الأداء",
            "preset_fast" to "توربو (500 اتصال)",
            "preset_balanced" to "متوازن (100 اتصال)",
            "preset_deep" to "خفي (20 اتصال)",
            "system_info" to "معلومات النظام والبيئة",
            "runtime_arch" to "بيئة التشغيل",
            "quick_localhost" to "المضيف المحلي (127.0.0.1)",
            "valid_target_ip" to "عنوان IPv4",
            "valid_target_domain" to "نطاق صالح",
            "whois_summary" to "ملخص هوية النطاق",
            "registrar" to "المسجل",
            "created_date" to "تاريخ الإنشاء",
            "expiry_date" to "تاريخ الانتهاء",
            "dns_records_count" to "السجلات المحللة",
            "placeholder_dns" to "النطاق (مثال: google.com)",
            "placeholder_whois" to "النطاق (مثال: wikipedia.org)",
            "ping_gateway" to "بينغ البوابة",
            "gateway_label" to "البوابة",
            "firewall_open" to "محيط شبكة مفتوح",
            "firewall_hardened" to "محيط شبكة محمي",
            "firewall_standard" to "ملف تعريف شبكة قياسي",
            "firewall_filtered" to "جدار ناري نشط",
            "load_more_ports" to "تحميل المزيد من المنافذ",
            "showing_ports_count" to "عرض {shown} من {total} منفذ مفتوح",
            "no_open_ports" to "لم يتم اكتشاف منافذ مفتوحة. المحيط مغلق بالكامل.",
            "search_ports_in_report" to "تصفية منافذ التقرير...",
            "device_mode" to "محاكي الأجهزة",
            "device_responsive" to "تفاعلي",
            "rotate_device" to "تدوير الشاشة",
            "snap_window" to "محاذاة النافذة مع الجهاز",
            "device_frame" to "إطار الجهاز",
            "os_fingerprint" to "بصمة نظام التشغيل",
            "download_report" to "تنزيل التقرير",
            "share_report" to "مشاركة",
            "detected_banner" to "توقيع الخدمة واللافتة المكتشفة",
            "security_advisory" to "الإرشادات الأمنية والتحصين",
            "tcp_listening" to "استماع TCP",
            "port_open" to "مفتوح",
            "export_report" to "تصدير وحفظ التقرير",
            "export_modal_title" to "تصدير وحفظ تقرير الفحص",
            "export_format_label" to "صيغة التصدير",
            "preview" to "معاينة حية للتصدير",
            "save_as_file" to "حفظ باسم...",
            "quick_save_downloads" to "حفظ في التنزيلات",
            "share_file_native" to "مشاركة النظام",
            "copy_content" to "نسخ المحتوى",
            "trend_improved" to "تحسن مستوى الأمان",
            "trend_declined" to "انخفاض مستوى الأمان",
            "trend_stable" to "استقرار الأمان",
            "peak_score" to "الأعلى",
            "min_score" to "الأدنى",
            "avg_score" to "المتوسط",
            "latest_score" to "الأحدث",
            "click_to_view" to "انقر على النقطة للتفاصيل",
            "trend_all" to "الكل",
            "trend_last_10" to "آخر 10",
            "trend_last_25" to "آخر 25",
            "trend_critical" to "عالي الخطورة فقط",
            "file_size" to "الحجم",
            "lines_count" to "الأسطر"
        ),
        "es" to mapOf(
            "dashboard" to "Panel",
            "tools" to "Herramientas",
            "reports" to "Informes",
            "settings" to "Ajustes",
            "scan" to "ESCANEAR",
            "stop" to "DETENER",
            "go" to "INICIAR",
            "target" to "IP o Dominio Objetivo",
            "advanced" to "Parámetros Avanzados",
            "active_services" to "Servicios Activos",
            "security_score" to "Puntuación de Seguridad",
            "no_services" to "No Se Encontraron Servicios",
            "language" to "Idioma y Región",
            "theme" to "Apariencia",
            "accent" to "Color de Énfasis",
            "dark" to "Modo Oscuro",
            "light" to "Modo Claro",
            "internal_ip" to "IP Interna",
            "public_ip" to "IP Pública",
            "interface" to "Adaptador de Red",
            "refresh" to "Actualizar",
            "threats_detected" to "Amenazas Detectadas",
            "device_profile" to "Perfil del Dispositivo",
            "firewall_perimeter" to "Perímetro",
            "socket_timeout" to "Tiempo de Espera",
            "ms" to "ms",
            "port_range" to "Rango de Puertos",
            "top_100" to "Top 100",
            "standard_ports" to "1-1024 Estándar",
            "web_ports" to "Puertos Web",
            "custom_range" to "Personalizado",
            "start_port" to "Puerto Inicial",
            "end_port" to "Puerto Final",
            "search_reports" to "Filtrar por objetivo o dispositivo...",
            "no_matching_reports" to "No se encontraron informes coincidentes",
            "global_export_format" to "FORMATO GLOBAL DE EXPORTACIÓN",
            "clear_history_title" to "¿Borrar Historial?",
            "clear_history_desc" to "¿Eliminar permanentemente todos los registros?",
            "clear_all" to "BORRAR TODO",
            "cancel" to "CANCELAR",
            "about" to "Acerca de",
            "support" to "Soporte",
            "feedback" to "Comentarios",
            "banner_grabbing" to "Captura de Banners",
            "full_port_scan" to "Escaneo Completo de Puertos",
            "multi_protocol" to "Multi-Protocolo",
            "stealth_mode" to "Modo Sigiloso",
            "not_enough_data" to "DATOS INSUFICIENTES"
        ),
        "fr" to mapOf(
            "dashboard" to "Tableau de Bord",
            "tools" to "Outils",
            "reports" to "Rapports",
            "settings" to "Paramètres",
            "scan" to "SCANNER",
            "stop" to "ARRÊTER",
            "go" to "DÉMARRER",
            "target" to "IP ou Domaine Cible",
            "advanced" to "Paramètres Avancés",
            "active_services" to "Services Actifs",
            "security_score" to "Score de Sécurité",
            "no_services" to "Aucun Service Détecté",
            "language" to "Langue et Région",
            "theme" to "Apparence",
            "accent" to "Couleur d'Accentuation",
            "dark" to "Mode Sombre",
            "light" to "Mode Clair",
            "internal_ip" to "IP Interne",
            "public_ip" to "IP Publique",
            "interface" to "Adaptateur Réseau",
            "refresh" to "Actualiser",
            "threats_detected" to "Menaces Détectées",
            "device_profile" to "Profil de l'Appareil",
            "firewall_perimeter" to "Périmètre",
            "socket_timeout" to "Délai d'Attente",
            "ms" to "ms",
            "port_range" to "Plage de Ports",
            "top_100" to "Top 100",
            "standard_ports" to "1-1024 Standard",
            "web_ports" to "Ports Web",
            "custom_range" to "Personnalisé",
            "start_port" to "Port Début",
            "end_port" to "Port Fin",
            "search_reports" to "Filtrer par cible ou appareil...",
            "no_matching_reports" to "Aucun rapport correspondant",
            "global_export_format" to "FORMAT D'EXPORTATION",
            "clear_history_title" to "Effacer l'Historique ?",
            "clear_history_desc" to "Supprimer définitivement tous les enregistrements ?",
            "clear_all" to "TOUT EFFACER",
            "cancel" to "ANNULER",
            "about" to "À Propos",
            "support" to "Support",
            "feedback" to "Commentaires",
            "banner_grabbing" to "Capture de Bannières",
            "full_port_scan" to "Scan Complet des Ports",
            "multi_protocol" to "Multi-Protocole",
            "stealth_mode" to "Mode Discret",
            "not_enough_data" to "DONNÉES INSUFFISANTES"
        ),
        "de" to mapOf(
            "dashboard" to "Übersicht",
            "tools" to "Werkzeuge",
            "reports" to "Berichte",
            "settings" to "Einstellungen",
            "scan" to "SCANNEN",
            "stop" to "STOPP",
            "go" to "START",
            "target" to "Ziel-IP / Domain",
            "advanced" to "Erweiterte Parameter",
            "active_services" to "Aktive Dienste",
            "security_score" to "Sicherheitsbewertung",
            "no_services" to "Keine Dienste Gefunden",
            "language" to "Sprache & Region",
            "theme" to "Erscheinungsbild",
            "accent" to "Akzentfarbe",
            "dark" to "Dunkelmodus",
            "light" to "Hellmodus",
            "internal_ip" to "Interne IP",
            "public_ip" to "Öffentliche IP",
            "interface" to "Netzwerkadapter",
            "refresh" to "Aktualisieren",
            "threats_detected" to "Erkannte Bedrohungen",
            "device_profile" to "Geräteprofil",
            "firewall_perimeter" to "Perimeter",
            "socket_timeout" to "Socket-Zeitüberschreitung",
            "ms" to "ms",
            "port_range" to "Portbereich",
            "top_100" to "Top 100",
            "standard_ports" to "1-1024 Standard",
            "web_ports" to "Web-Ports",
            "custom_range" to "Benutzerdefiniert",
            "start_port" to "Startport",
            "end_port" to "Endport",
            "search_reports" to "Nach Ziel oder Gerät filtern...",
            "no_matching_reports" to "Keine passenden Berichte gefunden",
            "global_export_format" to "EXPORTFORMAT",
            "clear_history_title" to "Verlauf Löschen?",
            "clear_history_desc" to "Alle Scanprotokolle dauerhaft löschen?",
            "clear_all" to "ALLES LÖSCHEN",
            "cancel" to "ABBRECHEN",
            "about" to "Über PortX",
            "support" to "Support",
            "feedback" to "Feedback",
            "banner_grabbing" to "Banner-Erfassung",
            "full_port_scan" to "Vollständiger Portscan",
            "multi_protocol" to "Multiprotokoll",
            "stealth_mode" to "Stealth-Modus",
            "not_enough_data" to "NICHT GENÜGEND DATEN"
        ),
        "ru" to mapOf(
            "dashboard" to "Панель",
            "tools" to "Инструменты",
            "reports" to "Отчеты",
            "settings" to "Настройки",
            "scan" to "СКАНИРОВАТЬ",
            "stop" to "СТОП",
            "go" to "ПУСК",
            "target" to "Целевой IP / Домен",
            "advanced" to "Расширенные параметры",
            "active_services" to "Активные службы",
            "security_score" to "Оценка безопасности",
            "no_services" to "Службы не найдены",
            "language" to "Язык и регион",
            "theme" to "Внешний вид",
            "accent" to "Акцентный цвет",
            "dark" to "Темный режим",
            "light" to "Светлый режим",
            "internal_ip" to "Внутренний IP",
            "public_ip" to "Публичный IP",
            "interface" to "Сетевой адаптер",
            "refresh" to "Обновить",
            "threats_detected" to "Обнаружены угрозы",
            "device_profile" to "Профиль устройства",
            "firewall_perimeter" to "Периметр",
            "socket_timeout" to "Тайм-аут сокета",
            "ms" to "мс",
            "port_range" to "Диапазон портов",
            "top_100" to "Топ 100",
            "standard_ports" to "1-1024",
            "web_ports" to "Веб-порты",
            "custom_range" to "Пользовательский",
            "start_port" to "Начальный порт",
            "end_port" to "Конечный порт",
            "search_reports" to "Фильтр по цели или устройству...",
            "no_matching_reports" to "Отчеты не найдены",
            "global_export_format" to "ФОРМАТ ЭКСПОРТА",
            "clear_history_title" to "Очистить историю?",
            "clear_history_desc" to "Удалить все записи сканирования навсегда?",
            "clear_all" to "УДАЛИТЬ ВСЕ",
            "cancel" to "ОТМЕНА",
            "about" to "О программе",
            "support" to "Поддержка",
            "feedback" to "Отзывы",
            "banner_grabbing" to "Захват баннеров",
            "full_port_scan" to "Полное сканирование портов",
            "multi_protocol" to "Мультипротокол",
            "stealth_mode" to "Скрытный режим",
            "not_enough_data" to "НЕДОСТАТОЧНО ДАННЫХ"
        ),
        "zh" to mapOf(
            "dashboard" to "仪表板",
            "tools" to "工具",
            "reports" to "报告",
            "settings" to "设置",
            "scan" to "扫描",
            "stop" to "停止",
            "go" to "运行",
            "target" to "目标 IP / 域名",
            "advanced" to "高级参数",
            "active_services" to "活动服务",
            "security_score" to "安全评分",
            "no_services" to "未发现服务",
            "language" to "语言与区域",
            "theme" to "外观",
            "accent" to "强调色",
            "dark" to "深色模式",
            "light" to "浅色模式",
            "internal_ip" to "内部 IP",
            "public_ip" to "公网 IP",
            "interface" to "网络适配器",
            "refresh" to "刷新",
            "threats_detected" to "检测到威胁",
            "device_profile" to "设备信息",
            "firewall_perimeter" to "边界防御",
            "socket_timeout" to "套接字超时",
            "ms" to "毫秒",
            "port_range" to "端口范围",
            "top_100" to "前 100 端口",
            "standard_ports" to "1-1024 常用端口",
            "web_ports" to "Web 端口",
            "custom_range" to "自定义范围",
            "start_port" to "起始端口",
            "end_port" to "结束端口",
            "search_reports" to "按目标或设备过滤...",
            "no_matching_reports" to "未找到匹配的报告",
            "global_export_format" to "全局导出格式",
            "clear_history_title" to "清空历史记录？",
            "clear_history_desc" to "永久删除所有扫描记录？",
            "clear_all" to "清空全部",
            "cancel" to "取消",
            "about" to "关于",
            "support" to "支持",
            "feedback" to "反馈",
            "banner_grabbing" to "横幅抓取",
            "full_port_scan" to "全端口扫描",
            "multi_protocol" to "多协议",
            "stealth_mode" to "隐身模式",
            "not_enough_data" to "数据不足"
        ),
        "ja" to mapOf("dashboard" to "ダッシュボード", "tools" to "ツール", "reports" to "レポート", "settings" to "設定"),
        "hi" to mapOf("dashboard" to "डैशबोर्ड", "tools" to "उपकरण", "reports" to "रिपोर्ट", "settings" to "सेटिंग्स")
    )

    fun get(key: String, lang: String): String {
        return strings[lang]?.get(key) ?: strings["en"]?.get(key) ?: key
    }
}
